# Generated by Django 3.2.12 on 2022-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
