# Generated by Django 3.2.12 on 2022-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
