# Generated by Django 3.2.12 on 2022-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_auto_20220623_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_devolucao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='nome_emprestado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='tempo_duracao',
            field=models.DateField(null=True),
        ),
    ]
