# Generated by Django 3.2.12 on 2022-07-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_auto_20220707_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livros'),
            preserve_default=False,
        ),
    ]
