# Generated by Django 3.2.12 on 2022-07-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_auto_20220708_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
