# Generated by Django 3.2.12 on 2022-07-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_remove_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
    ]
